### ISSUE TITLE
No sound on sideloaded Microsoft Edge

### ISSUE THREAD

**Issue by shirounanashi** [Vanilla-OS/sideload-utility#12]
I installed Microsoft Edge using sideload-utility and the browser does not play sound
Vanilla OS version : 2 Orchid id 127

**Comment by taukakao** [comment]
Could you try installing libasound2 with:
sudo apt update
sudo apt install libasound2
?

**Comment by shirounanashi** [comment]
Hi @taukakao , It says I already have the latest version, and there's still no sound

**Comment by taukakao** [comment]
Could you try to install some app from the official repos that plays sounds and try if it works there?

**Comment by shirounanashi** [comment]
I installed Firefox from the store, and it plays sound. I don't know if that's what you meant

**Comment by taukakao** [comment]
Yeah, then it seems to me that this is a problem with Edge itself and not with sideload or the container. 
You might want to try installing Edge from the store or with the flatpak command.

**Comment by shirounanashi** [comment]
@taukakao I installed it in the store and it actually has sound. I don't know if this is a solution to the problem, as other apps installed via sideload may have this same problem. If you think it's a problem with Edge itself, you can close the issue

**Comment by taukakao** [comment]
I would argue as long as this doesn't happen again with another app it's considered an Edge specific bug.
