### ISSUE TITLE
TypeError raised by Done button

### ISSUE THREAD

**Issue by Mizumo-prjkt** [Vanilla-OS/sideload-utility#8]
![image](https://github.com/Vanilla-OS/sideload-utility/assets/70519093/7582d803-6da9-4ddb-9d92-f8d4c8b6f857)
![image](https://github.com/Vanilla-OS/sideload-utility/assets/70519093/d3c4ccf6-ecde-45c6-a0c5-a295e3bcffd1)

*This has been going on for hours earlier and decided to give up*

I am trying to install Neko, a Tachiyomi fork for browsing manga with Mangadex as a service

I used a universal version of the APK since my unit is actually x86_64

I noticed that Sideload didnt do anything to install this apk so i decided to retry and retry, wait for an hour and aborted, and made this report

And here is also my suggestion since i found the issue:

### Waydroid wasn't installed and i didnt know.

So i used vsx and it is installing the waydroid image, will take a while since sourceforge is slow. 

**My recommendation**

Maybe let sideload check if Waydroid is present in the machine because the user may think that Sideloading APK may be a lie

I'll also submit my findings on r/VanillaOS on Reddit later as im on a quest to bug hunting

Have a good day!

**Comment by mirkobrombin** [comment]
Waydroid initialization were introduced here https://github.com/Vanilla-OS/sideload-utility/commit/3db0891a1afab3db5128b8a42098a62060049033

There is chance you were hitting this bug https://github.com/Vanilla-OS/sideload-utility/commit/ba6d6726908baeba4e4bcfd69aa2dbe6587b76a2

We are building and releasing an update to ensure the sideload app gets updated.

**Comment by Mizumo-prjkt** [comment]
Thank you.

Also, how to get logs on a particular situation so I can maybe copy-paste it? So to ease the debug on your side?

**Comment by mirkobrombin** [comment]
> Thank you.
> 
> Also, how to get logs on a particular situation so I can maybe copy-paste it? So to ease the debug on your side?

Running it via CLI:

```
vanilla-sideload --install <path_to_deb_or_apk>
```

**Comment by Mizumo-prjkt** [comment]
```
scara@apx-vso-pico:~/Downloads$ vanilla-sideload --install neko-universal.apk
Sideload 0.1.0
TypeError: Must be number, not NoneType
Traceback (most recent call last):
  File "/usr/share/vanilla-sideload/vanilla_sideload/views/install.py", line 154, in __on_install_clicked
    self.__pkg.install_cmd_as_list,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/vanilla-sideload/vanilla_sideload/backend/types.py", line 122, in install_cmd_as_list
    return shlex.split(self.install_cmd)
                       ^^^^^^^^^^^^^^^^
  File "/usr/share/vanilla-sideload/vanilla_sideload/backend/types.py", line 118, in install_cmd
    return SideloadUtils.get_vso_cmd(f"android install --local {self.path}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/vanilla-sideload/vanilla_sideload/backend/utils.py", line 35, in get_vso_cmd
    if os.path.exists(f"{os.environ['VSO_PATH']}/vso"):
                         ~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'VSO_PATH'

``` 

and then its stuck, and didn't do anything

as for waydroid status:

```
scara@apx-vso-pico:~$ vso android status
INITIALIZED
scara@apx-vso-pico:~$ 
```

but sadly i cant check whether waydroid is really running as im isolated within the core system

**Comment by Mizumo-prjkt** [comment]
Even declaring full path, not working

```
scara@apx-vso-pico:~/Downloads$ vanilla-sideload --install /home/scara/Downloads/neko-universal.apk
Sideload 0.1.0
TypeError: Must be number, not NoneType
Traceback (most recent call last):
  File "/usr/share/vanilla-sideload/vanilla_sideload/views/install.py", line 154, in __on_install_clicked
    self.__pkg.install_cmd_as_list,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/vanilla-sideload/vanilla_sideload/backend/types.py", line 122, in install_cmd_as_list
    return shlex.split(self.install_cmd)
                       ^^^^^^^^^^^^^^^^
  File "/usr/share/vanilla-sideload/vanilla_sideload/backend/types.py", line 118, in install_cmd
    return SideloadUtils.get_vso_cmd(f"android install --local {self.path}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/vanilla-sideload/vanilla_sideload/backend/utils.py", line 35, in get_vso_cmd
    if os.path.exists(f"{os.environ['VSO_PATH']}/vso"):
                         ~~~~~~~~~~^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'VSO_PATH'
```

**Comment by mirkobrombin** [comment]
Have you updated your system to receive the fix? That exact bug was fixed several hours ago

**Comment by Mizumo-prjkt** [comment]
ok i missed that

anyways, updated the system and 
![image](https://github.com/Vanilla-OS/sideload-utility/assets/70519093/807c32e5-0940-4320-9071-344657af702e)

![image](https://github.com/Vanilla-OS/sideload-utility/assets/70519093/eadeefe8-16b5-49e8-b847-56508d3e8e2a)
horray

![image](https://github.com/Vanilla-OS/sideload-utility/assets/70519093/373a8ced-8038-4114-9c77-c969b3d5d0e9)
but pressing "Done" says this
